### ISSUE TITLE
迷你分时图能不能也加个totalCount判断，然后绘制迷你分时图的时候还没收盘的时候，右边是有空间的，类似分时图那样

### ISSUE THREAD

**Issue by Rethen** [yangsanning/StockView#1]
![TIM图片20200605150104](https://user-images.githubusercontent.com/7802673/83846593-6b1b0d00-a73d-11ea-8e68-a790264337ce.jpg)

**Comment by yangsanning** [comment]
才看到 issue，最新代码已添加，感谢提建议~

**Comment by chapliny** [comment]
@Rethen 你好，请问 这种列表 里面这么多分时图 怎么保证滑动不卡顿的啊

**Comment by Rethen** [comment]
>其实不会卡顿吧，除非你一秒内过百的刷新

**Comment by chapliny** [comment]
我是这么做的，分时图的数据比较多，和股票的基础数据分开的，然后滑动的时候拿到 当前显示的索引，再根据索引去请求分时图的数据，然后再赋值分时图。请问有没有其他更好的方式

**Comment by Rethen** [comment]
> 我是这么做的，分时图的数据比较多，和股票的基础数据分开的，然后滑动的时候拿到 当前显示的索引，再根据索引去请求分时图的数据，然后再赋值分时图。请问有没有其他更好的方式

完全不需要这么做的吧，除非你在adapter做了太多的事情，我是数据绑定的方式，所有的数据处理不在adapter中去做，而是在接收到数据的时候，就已经做了dto----vo的操作，所以在滑动的时候没有任何逻辑的判断

**Comment by chapliny** [comment]
> > 我是这么做的，分时图的数据比较多，和股票的基础数据分开的，然后滑动的时候拿到 当前显示的索引，再根据索引去请求分时图的数据，然后再赋值分时图。请问有没有其他更好的方式
> 
> 完全不需要这么做的吧，除非你在adapter做了太多的事情，我是数据绑定的方式，所有的数据处理不在adapter中去做，而是在接收到数据的时候，就已经做了dto----vo的操作，所以在滑动的时候没有任何逻辑的判断

没有在adapter 里做请求，是在拿到基础数据后请求的，然后在 notifyItemRangeChanged 到指定item，这么做的原因还是分时的数据太多。如果列表里有100条股票数据，那分时 最少就是*240，如果还有美股的就更多了

**Comment by Rethen** [comment]
> > > 我是这么做的，分时图的数据比较多，和股票的基础数据分开的，然后滑动的时候拿到 当前显示的索引，再根据索引去请求分时图的数据，然后再赋值分时图。请问有没有其他更好的方式
> > 
> > 
> > 完全不需要这么做的吧，除非你在adapter做了太多的事情，我是数据绑定的方式，所有的数据处理不在adapter中去做，而是在接收到数据的时候，就已经做了dto----vo的操作，所以在滑动的时候没有任何逻辑的判断
> 
> 没有在adapter 里做请求，是在拿到基础数据后请求的，然后在 notifyItemRangeChanged 到指定item，这么做的原因还是分时的数据太多。如果列表里有100条股票数据，那分时 最少就是*240，如果还有美股的就更多了

能给我看下你Adapter都做了哪些操作？

**Comment by chapliny** [comment]
> > > > 我是这么做的，分时图的数据比较多，和股票的基础数据分开的，然后滑动的时候拿到 当前显示的索引，再根据索引去请求分时图的数据，然后再赋值分时图。请问有没有其他更好的方式
> > > 
> > > 
> > > 完全不需要这么做的吧，除非你在adapter做了太多的事情，我是数据绑定的方式，所有的数据处理不在adapter中去做，而是在接收到数据的时候，就已经做了dto----vo的操作，所以在滑动的时候没有任何逻辑的判断
> > 
> > 
> > 没有在adapter 里做请求，是在拿到基础数据后请求的，然后在 notifyItemRangeChanged 到指定item，这么做的原因还是分时的数据太多。如果列表里有100条股票数据，那分时 最少就是*240，如果还有美股的就更多了
> 
> 能给我看下你Adapter都做了哪些操作？

![image](https://user-images.githubusercontent.com/3133328/106436459-12a83500-64af-11eb-8079-8491de86c2dd.png)
![image](https://user-images.githubusercontent.com/3133328/106436540-2eabd680-64af-11eb-8ed3-4ba1d28e4793.png)

**Comment by Rethen** [comment]
getMinuteData中是不是做了很多处理，我觉得getMinuteData可以放在外面，不要adapter中去做转换，adapter中传进去直接就是可以使用的fenshitime对象不就好了，一个LineInfoBean 对应一个FenShiTime对象

**Comment by chapliny** [comment]
就是把自己的对象转换成 fenshitime 对象。
不过你说的也对，不在adapter 做耗时操作

**Comment by Rethen** [comment]
> 就是把自己的对象转换成 fenshitime 对象。
> 不过你说的也对，不在adapter 做耗时操作

转换如果只是简单的处理倒还好，如果有涉及遍历什么的，影响就大了

**Comment by Rethen** [comment]
> 就是把自己的对象转换成 fenshitime 对象。
> 不过你说的也对，不在adapter 做耗时操作


分时点的集合，你肯定是要遍历的，adapter最忌讳遍历

**Comment by chapliny** [comment]
> > 就是把自己的对象转换成 fenshitime 对象。
> > 不过你说的也对，不在adapter 做耗时操作
> 
> 分时点的集合，你肯定是要遍历的，adapter最忌讳遍历

嗯嗯，好的，感谢感谢

**Comment by chapliny** [comment]
有一个问题，增加一个删除一个关注的股票的时候会有部分虚线。我增加或删除一条数据
![image](https://user-images.githubusercontent.com/3133328/108944854-8dbbd000-7696-11eb-966b-79d716ee96dd.png)

**Comment by yangsanning** [comment]
> 有一个问题，增加一个删除一个关注的股票的时候会有部分虚线。我增加或删除一条数据
> ![image](https://user-images.githubusercontent.com/3133328/108944854-8dbbd000-7696-11eb-966b-79d716ee96dd.png)

移步 https://github.com/IT-DanielWu/StockView/issues/5
