### ISSUE TITLE
其实还有一个问题

### ISSUE THREAD

**Issue by Rethen** [yangsanning/StockView#3]
迷你分时图最小值 和最大值的计算，应该加入昨天的收盘价，这样子中线的位置才没问题，要不然有中线消失的情况

**Comment by yangsanning** [comment]
目前不显示中线是因为 `昨收不在最大值与最小值范围内` ，你这边是不在范围内也需要显示中线？

**Comment by Rethen** [comment]
是的，是有这样的需求

**Comment by yangsanning** [comment]
那这种情况下， 中线需要如何展示？最上与最下？

**Comment by Rethen** [comment]
是啊，就是最上或者最下，其实就是昨收价低于今日最低价或者昨收价高于今日最高价

**Comment by yangsanning** [comment]
v1.2.2版本增加了一个 `alwaysShowDottedLine ` 属性，用于控制中线是否始终显示（默认**false**）
