### ISSUE TITLE
能不能搞个小图不显示底下阴影的开关，有些管理层审美有问题，会觉得阴影不好看

### ISSUE THREAD

**Issue by Rethen** [yangsanning/StockView#4]
能不能搞个小图不显示底下阴影的开关，有些管理层审美有问题，会觉得阴影不好看

**Comment by yangsanning** [comment]
这个可以

**Comment by Rethen** [comment]
> 这个可以

你是说设置渐变底部颜色设置成透明吗？

**Comment by yangsanning** [comment]
[v1.2.3](https://github.com/yangsanning/StockView/releases/tag/v1.2.3) 版本增加了一个 `enableGradientBottom` 属性，用于控制渐变是否启用（默认 true）
