### ISSUE TITLE
MiniFenShiView 在RecyclerView 中增加或删除出现  多余线灰色的线，如下图

### ISSUE THREAD

**Issue by chapliny** [yangsanning/StockView#5]
![image](https://user-images.githubusercontent.com/3133328/108952385-56542000-76a4-11eb-9c98-9294a1cd9e71.png)
有时重新刷新也能好，

**Comment by yangsanning** [comment]
你好！这并不是一个bug，该线是昨收线。

#### 解决方案：
因为最近太忙，暂时没有时间去维护该库，如果你比较紧急的话，可以自行禁止如下代码：
`// 绘制默认中线
drawLastClose(canvas, getTopTableMinY() / 2);`

感谢提问题~

**Comment by chapliny** [comment]
不是昨收线，昨收应该是一条直线，这个是有曲线的，应是错乱了。如果列表排序了也会有这个问题。排序我是调用的 notifyDataSetChanged();

**Comment by chapliny** [comment]
//绘制默认中线
drawLastClose(canvas, getTopTableMinY() / 2); 
这个已经去除了

**Comment by chapliny** [comment]
> 你好！这并不是一个bug，该线是昨收线。
> 
> #### 解决方案：
> 因为最近太忙，暂时没有时间去维护该库，如果你比较紧急的话，可以自行禁止如下代码：
> `// 绘制默认中线 drawLastClose(canvas, getTopTableMinY() / 2);`
> 
> 感谢提问题~
//绘制默认中线
drawLastClose(canvas, getTopTableMinY() / 2);去除了，还是一样的
![image](https://user-images.githubusercontent.com/3133328/108957735-f4e47f00-76ac-11eb-80ad-f4044532c30a.png)

**Comment by IT-DanielWu** [comment]
> > 你好！这并不是一个bug，该线是昨收线。
> > #### 解决方案：
> > 因为最近太忙，暂时没有时间去维护该库，如果你比较紧急的话，可以自行禁止如下代码：
> > `// 绘制默认中线 drawLastClose(canvas, getTopTableMinY() / 2);`
> > 感谢提问题~
> > //绘制默认中线
> > drawLastClose(canvas, getTopTableMinY() / 2);去除了，还是一样的
> > ![image](https://user-images.githubusercontent.com/3133328/108957735-f4e47f00-76ac-11eb-80ad-f4044532c30a.png)

不好意思，前面没注意看图，以为你是不想要这条线。那段代码无需注释掉。
你检查一下你的数据，昨收是否一致。

**Comment by yangsanning** [comment]
> > 你好！这并不是一个bug，该线是昨收线。
> > #### 解决方案：
> > 因为最近太忙，暂时没有时间去维护该库，如果你比较紧急的话，可以自行禁止如下代码：
> > `// 绘制默认中线 drawLastClose(canvas, getTopTableMinY() / 2);`
> > 感谢提问题~
> > //绘制默认中线
> > drawLastClose(canvas, getTopTableMinY() / 2);去除了，还是一样的
> > ![image](https://user-images.githubusercontent.com/3133328/108957735-f4e47f00-76ac-11eb-80ad-f4044532c30a.png)

不好意思，没注意看图，那段代码无需删除。
你找一段绘制错误的数据，然后单独一个 MiniFenShiView 看看有没有异常，不放在RecyclerView上，或在Demo上运行

**Comment by chapliny** [comment]
> > > 你好！这并不是一个bug，该线是昨收线。
> > > #### 解决方案：
> > > 因为最近太忙，暂时没有时间去维护该库，如果你比较紧急的话，可以自行禁止如下代码：
> > > `// 绘制默认中线 drawLastClose(canvas, getTopTableMinY() / 2);`
> > > 感谢提问题~
> > > //绘制默认中线
> > > drawLastClose(canvas, getTopTableMinY() / 2);去除了，还是一样的
> > > ![image](https://user-images.githubusercontent.com/3133328/108957735-f4e47f00-76ac-11eb-80ad-f4044532c30a.png)
> 
> 不好意思，没注意看图，那段代码无需删除。
> 你找一段绘制错误的数据，然后单独一个 MiniFenShiView 看看有没有异常，不放在RecyclerView上，或在Demo上运行

不是错误数据的问题，只要更改过你数据位置，或增加减少过 就有这个问题。单独放到demo 上view 里是没问题的

**Comment by yangsanning** [comment]
> > > > 你好！这并不是一个bug，该线是昨收线。
> > > > #### 解决方案：
> > > > 因为最近太忙，暂时没有时间去维护该库，如果你比较紧急的话，可以自行禁止如下代码：
> > > > `// 绘制默认中线 drawLastClose(canvas, getTopTableMinY() / 2);`
> > > > 感谢提问题~
> > > > //绘制默认中线
> > > > drawLastClose(canvas, getTopTableMinY() / 2);去除了，还是一样的
> > > > ![image](https://user-images.githubusercontent.com/3133328/108957735-f4e47f00-76ac-11eb-80ad-f4044532c30a.png)
> > 
> > 
> > 不好意思，没注意看图，那段代码无需删除。
> > 你找一段绘制错误的数据，然后单独一个 MiniFenShiView 看看有没有异常，不放在RecyclerView上，或在Demo上运行
> 
> 不是错误数据的问题，只要更改过你数据位置，或增加减少过 就有这个问题。单独放到demo 上view 里是没问题的

我找个时间帮你看看，如果方便的话，把相关数据发我邮箱：ysn_2020@163.com

**Comment by chapliny** [comment]
好的，晚点我整理一份代码，感谢

**Comment by yangsanning** [comment]
> 好的，晚点我整理一份代码，感谢

找到问题了：[v1.2.3 版本](https://github.com/IT-DanielWu/StockView/issues/4)遗留的bug

#### 解决方案：
绘制结束后，须将画笔重置。
![image](https://user-images.githubusercontent.com/20766133/109090041-53f9d080-774d-11eb-848c-41cab764b173.png)

感谢提bug~

**Comment by chapliny** [comment]
> > 好的，晚点我整理一份代码，感谢
> 
> 找到问题了：[v1.2.3 版本](https://github.com/IT-DanielWu/StockView/issues/4)遗留的bug
> 
> #### 解决方案：
> 绘制结束后，须将画笔重置。
> ![image](https://user-images.githubusercontent.com/20766133/109090041-53f9d080-774d-11eb-848c-41cab764b173.png)
> 
> 感谢提bug~

感谢感谢

**Comment by chapliny** [comment]
有个问请教下
我已经绘制好的线 怎么改变颜色，把所有的线remove 了重新绘制一遍吗？还是有其他方法
